platform :ios, '15.0'

target 'mOrganization' do
  	use_frameworks!
	
	pod 'RxSwift'
	pod 'RxCocoa'
  pod 'RxGesture'
	pod 'SwiftGen'
  pod 'FirebaseAuth'
  pod 'FirebaseStorage'
  pod 'FirebaseFirestore'
  pod 'FirebaseFirestoreSwift'
  
end
